package com.jicka.core;

/**
 *
 * @author Mickael Boudignot
 */
public class Configuration {

    /**
     * A public configuration to store the number of total static field in the
     * program. This class will be auto-generated by asm during convertion an
     * inject the good value for this configuration.
     */
    public static int STATICMAXSIZE = 0;

    /**
     * A public configuration to store the number of total instance field in the
     * program. This class will be auto-generated by asm during convertion an
     * inject the good value for this configuration.
     */
    public static int FIELDMAXSIZE = 0;
}
